### ISSUE TITLE
TD088 Commercial compatible?

### ISSUE THREAD

**Issue by jBachalo** [mourendxu/TD-OpenCV3TOP#1]
Hi
Have the commercial version of TD88 and am trying to launch the demo. Everything is installed correctly but still get an error on the CPlusPlus TOP

"The loaded .dll does not contain the required functions for the CPlusPlus interface"

Is there a chance this will only work with Touch 099 Commercial?

**Comment by mourendxu** [comment]
Hi, 

the compiled version wouldn't work on 88, because it was compiled against the 099 headers, and specifically against the build number I posted.

But, if you download the source, and replace the default headers, you should be able to compile it for 088. It should be fairly straightforward, if you have some experience with compiling code. TD's wiki also contains some instructions on how to do this.

Thanks.
